// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto(in *jlexer.Lexer, out *PreviewAdvertCard) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "preview":
			(out.Preview).UnmarshalEasyJSON(in)
		case "is_saved":
			out.IsSaved = bool(in.Bool())
		case "is_viewed":
			out.IsViewed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto(out *jwriter.Writer, in PreviewAdvertCard) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"preview\":"
		out.RawString(prefix[1:])
		(in.Preview).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"is_saved\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsSaved))
	}
	{
		const prefix string = ",\"is_viewed\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsViewed))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PreviewAdvertCard) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PreviewAdvertCard) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PreviewAdvertCard) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PreviewAdvertCard) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto(l, v)
}
func easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto1(in *jlexer.Lexer, out *PreviewAdvert) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "seller_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.SellerId).UnmarshalText(data))
			}
		case "category_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.CategoryId).UnmarshalText(data))
			}
		case "title":
			out.Title = string(in.String())
		case "price":
			out.Price = uint(in.Uint())
		case "image_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ImageId).UnmarshalText(data))
			}
		case "status":
			out.Status = AdvertStatus(in.String())
		case "location":
			out.Location = string(in.String())
		case "has_delivery":
			out.HasDelivery = bool(in.Bool())
		case "promoted_until":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.PromotedUntil).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto1(out *jwriter.Writer, in PreviewAdvert) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"seller_id\":"
		out.RawString(prefix)
		out.RawText((in.SellerId).MarshalText())
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.RawText((in.CategoryId).MarshalText())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Uint(uint(in.Price))
	}
	{
		const prefix string = ",\"image_id\":"
		out.RawString(prefix)
		out.RawText((in.ImageId).MarshalText())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"location\":"
		out.RawString(prefix)
		out.String(string(in.Location))
	}
	{
		const prefix string = ",\"has_delivery\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasDelivery))
	}
	{
		const prefix string = ",\"promoted_until\":"
		out.RawString(prefix)
		out.Raw((in.PromotedUntil).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PreviewAdvert) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PreviewAdvert) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PreviewAdvert) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PreviewAdvert) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto1(l, v)
}
func easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto2(in *jlexer.Lexer, out *MyPreviewAdvertCard) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "preview":
			(out.Preview).UnmarshalEasyJSON(in)
		case "views_number":
			out.ViewsNumber = uint(in.Uint())
		case "saves_number":
			out.SavesNumber = uint(in.Uint())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto2(out *jwriter.Writer, in MyPreviewAdvertCard) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"preview\":"
		out.RawString(prefix[1:])
		(in.Preview).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"views_number\":"
		out.RawString(prefix)
		out.Uint(uint(in.ViewsNumber))
	}
	{
		const prefix string = ",\"saves_number\":"
		out.RawString(prefix)
		out.Uint(uint(in.SavesNumber))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyPreviewAdvertCard) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyPreviewAdvertCard) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyPreviewAdvertCard) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyPreviewAdvertCard) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto2(l, v)
}
func easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto3(in *jlexer.Lexer, out *AdvertRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "category_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.CategoryId).UnmarshalText(data))
			}
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "price":
			out.Price = uint(in.Uint())
		case "status":
			out.Status = AdvertStatus(in.String())
		case "has_delivery":
			out.HasDelivery = bool(in.Bool())
		case "location":
			out.Location = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto3(out *jwriter.Writer, in AdvertRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.CategoryId).MarshalText())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Uint(uint(in.Price))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"has_delivery\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasDelivery))
	}
	{
		const prefix string = ",\"location\":"
		out.RawString(prefix)
		out.String(string(in.Location))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdvertRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdvertRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdvertRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdvertRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto3(l, v)
}
func easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto4(in *jlexer.Lexer, out *AdvertCard) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "advert":
			(out.Advert).UnmarshalEasyJSON(in)
		case "is_saved":
			out.IsSaved = bool(in.Bool())
		case "is_viewed":
			out.IsViewed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto4(out *jwriter.Writer, in AdvertCard) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"advert\":"
		out.RawString(prefix[1:])
		(in.Advert).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"is_saved\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsSaved))
	}
	{
		const prefix string = ",\"is_viewed\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsViewed))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdvertCard) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdvertCard) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdvertCard) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdvertCard) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto4(l, v)
}
func easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto5(in *jlexer.Lexer, out *Advert) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "seller_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.SellerId).UnmarshalText(data))
			}
		case "category_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.CategoryId).UnmarshalText(data))
			}
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "price":
			out.Price = uint(in.Uint())
		case "image_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ImageId).UnmarshalText(data))
			}
		case "status":
			out.Status = AdvertStatus(in.String())
		case "has_delivery":
			out.HasDelivery = bool(in.Bool())
		case "location":
			out.Location = string(in.String())
		case "saves_number":
			out.SavesNumber = uint(in.Uint())
		case "views_number":
			out.ViewsNumber = uint(in.Uint())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		case "promoted_until":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.PromotedUntil).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto5(out *jwriter.Writer, in Advert) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"seller_id\":"
		out.RawString(prefix)
		out.RawText((in.SellerId).MarshalText())
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.RawText((in.CategoryId).MarshalText())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Uint(uint(in.Price))
	}
	{
		const prefix string = ",\"image_id\":"
		out.RawString(prefix)
		out.RawText((in.ImageId).MarshalText())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"has_delivery\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasDelivery))
	}
	{
		const prefix string = ",\"location\":"
		out.RawString(prefix)
		out.String(string(in.Location))
	}
	{
		const prefix string = ",\"saves_number\":"
		out.RawString(prefix)
		out.Uint(uint(in.SavesNumber))
	}
	{
		const prefix string = ",\"views_number\":"
		out.RawString(prefix)
		out.Uint(uint(in.ViewsNumber))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"promoted_until\":"
		out.RawString(prefix)
		out.Raw((in.PromotedUntil).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Advert) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Advert) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA66148a6EncodeGithubComGoParkMailRu20242BogoSortInternalEntityDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Advert) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Advert) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA66148a6DecodeGithubComGoParkMailRu20242BogoSortInternalEntityDto5(l, v)
}
