// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Advert ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Advert ) UnmarshalJSON([]byte) error { return nil }
func ( Advert ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Advert ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Advert *Advert

func ( AdvertCard ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AdvertCard ) UnmarshalJSON([]byte) error { return nil }
func ( AdvertCard ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AdvertCard ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AdvertCard *AdvertCard

func ( AdvertRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AdvertRequest ) UnmarshalJSON([]byte) error { return nil }
func ( AdvertRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AdvertRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AdvertRequest *AdvertRequest

func ( AdvertStatus ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AdvertStatus ) UnmarshalJSON([]byte) error { return nil }
func ( AdvertStatus ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AdvertStatus ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AdvertStatus *AdvertStatus

func ( MyPreviewAdvertCard ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MyPreviewAdvertCard ) UnmarshalJSON([]byte) error { return nil }
func ( MyPreviewAdvertCard ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MyPreviewAdvertCard ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MyPreviewAdvertCard *MyPreviewAdvertCard

func ( PreviewAdvert ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PreviewAdvert ) UnmarshalJSON([]byte) error { return nil }
func ( PreviewAdvert ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PreviewAdvert ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PreviewAdvert *PreviewAdvert

func ( PreviewAdvertCard ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PreviewAdvertCard ) UnmarshalJSON([]byte) error { return nil }
func ( PreviewAdvertCard ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PreviewAdvertCard ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PreviewAdvertCard *PreviewAdvertCard
