// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Login ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Login ) UnmarshalJSON([]byte) error { return nil }
func ( Login ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Login ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Login *Login

func ( Signup ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Signup ) UnmarshalJSON([]byte) error { return nil }
func ( Signup ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Signup ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Signup *Signup

func ( UpdatePassword ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UpdatePassword ) UnmarshalJSON([]byte) error { return nil }
func ( UpdatePassword ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UpdatePassword ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UpdatePassword *UpdatePassword
