// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AddAdvertToUserCartRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddAdvertToUserCartRequest ) UnmarshalJSON([]byte) error { return nil }
func ( AddAdvertToUserCartRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddAdvertToUserCartRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddAdvertToUserCartRequest *AddAdvertToUserCartRequest

func ( Cart ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Cart ) UnmarshalJSON([]byte) error { return nil }
func ( Cart ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Cart ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Cart *Cart

func ( CartPurchase ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CartPurchase ) UnmarshalJSON([]byte) error { return nil }
func ( CartPurchase ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CartPurchase ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CartPurchase *CartPurchase

func ( CartResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CartResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CartResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CartResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CartResponse *CartResponse

func ( DeleteAdvertFromUserCartRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteAdvertFromUserCartRequest ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteAdvertFromUserCartRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteAdvertFromUserCartRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteAdvertFromUserCartRequest *DeleteAdvertFromUserCartRequest
