// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Category ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Category ) UnmarshalJSON([]byte) error { return nil }
func ( Category ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Category ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Category *Category
