// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PriceHistoryResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PriceHistoryResponse ) UnmarshalJSON([]byte) error { return nil }
func ( PriceHistoryResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PriceHistoryResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PriceHistoryResponse *PriceHistoryResponse
