// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PurchaseRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PurchaseRequest ) UnmarshalJSON([]byte) error { return nil }
func ( PurchaseRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PurchaseRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PurchaseRequest *PurchaseRequest

func ( PurchaseResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PurchaseResponse ) UnmarshalJSON([]byte) error { return nil }
func ( PurchaseResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PurchaseResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PurchaseResponse *PurchaseResponse
