// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package dto

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (User) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*User) UnmarshalJSON([]byte) error        { return nil }
func (User) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*User) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_User *User

func (UserUpdate) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UserUpdate) UnmarshalJSON([]byte) error        { return nil }
func (UserUpdate) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UserUpdate) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserUpdate *UserUpdate
