{
 "title": "Emporium_BogoSort",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values({__name__=~\".*_total_hits_count\"}, service)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values({__name__=~\".*_total_hits_count\"}, method)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(app_total_hits_count, path)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "95th Percentile Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (service, method, path, le) (\n  rate(app_code_bucket{service=~\"$service\", method=~\"$method\", path=~\"$path\"}[5m])\n))",
     "legendFormat": "{{service}} - {{method}} - {{path}} 95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, method, le) (\n  rate(static_code_bucket{service=~\"$service\", method=~\"$method\"}[5m])\n))",
     "legendFormat": "{{service}} - {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, method, le) (\n  rate(auth_code_bucket{service=~\"$service\", method=~\"$method\"}[5m])\n))",
     "legendFormat": "{{service}} - {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, method, le) (\n  rate(cart_purchase_code_bucket{service=~\"$service\", method=~\"$method\"}[5m])\n))",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service, method, path) (\n  rate(app_code_sum{service=~\"$service\", method=~\"$method\", path=~\"$path\"}[5m])\n) / sum by (service, method, path) (\n  rate(app_code_count{service=~\"$service\", method=~\"$method\", path=~\"$path\"}[5m])\n)",
     "legendFormat": "{{service}} - {{method}} - {{path}} Average"
    },
    {
     "expr": "sum by (service, method) (\n  rate(auth_code_sum{service=~\"$service\", method=~\"$method\"}[5m])\n) / sum by (service, method) (\n  rate(auth_code_count{service=~\"$service\", method=~\"$method\"}[5m])\n)",
     "legendFormat": "{{service}} - {{method}} Average"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_free_bytes{fstype!=\"tmpfs\", instance=~\"$instance\"} / node_filesystem_size_bytes{fstype!=\"tmpfs\", instance=~\"$instance\"}) * 100)\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!=\"tmpfs\", instance=~\"$instance\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\", instance=~\"$instance\"}) / node_filesystem_size_bytes{fstype!=\"tmpfs\", instance=~\"$instance\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!=\"tmpfs\", instance=~\"$instance\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (\n  rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])\n) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Total Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "App Error Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service, method, path) (\n  rate(app_error_hits_count{service=~\"$service\", method=~\"$method\", path=~\"$path\"}[5m])\n)",
     "legendFormat": "{{service}} - {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Auth Error Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum by (service, method) (auth_error_hits_count{service=~\"$service\", method=~\"$method\"})",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  },
  {
   "title": "Static Error Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (service, method) (static_error_hits_count{service=~\"$service\", method=~\"$method\"})",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  },
  {
   "title": "Cart_purchase Error Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by (service, method) (cart_purchase_error_hits_count{service=~\"$service\", method=~\"$method\"})",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  },
  { "title": "Total Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Total Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service, method, path) (\n  rate(app_total_hits_count{service=~\"$service\", method=~\"$method\", path=~\"$path\"}[5m])\n)",
     "legendFormat": "{{service}} - {{path}}"
    },
    {
     "expr": "sum by (service, method) (rate(auth_total_hits_count{service=~\"$service\", method=~\"$method\"}[5m]))",
     "legendFormat": "{{service}} - {{method}}"
    },
    {
     "expr": "sum by (service, method) (rate(static_total_hits_count{service=~\"$service\", method=~\"$method\"}[5m]))",
     "legendFormat": "{{service}} - {{method}}"
    },
    {
     "expr": "sum by (service, method) (rate(cart_purchase_total_hits_count{service=~\"$service\", method=~\"$method\"}[5m]))",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  }
 ]
}