global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['app:8080']

  - job_name: 'auth'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['auth:7051']

  - job_name: 'cart_purchase'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['cart_purchase:7052']

  - job_name: 'static'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['static:7053']
  
  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node_exporter:9100' ]
