// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/cart.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/go-park-mail-ru/2024_2_BogoSort/internal/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
)

// MockCart is a mock of Cart interface.
type MockCart struct {
	ctrl     *gomock.Controller
	recorder *MockCartMockRecorder
}

// MockCartMockRecorder is the mock recorder for MockCart.
type MockCartMockRecorder struct {
	mock *MockCart
}

// NewMockCart creates a new mock instance.
func NewMockCart(ctrl *gomock.Controller) *MockCart {
	mock := &MockCart{ctrl: ctrl}
	mock.recorder = &MockCartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCart) EXPECT() *MockCartMockRecorder {
	return m.recorder
}

// AddAdvertToCart mocks base method.
func (m *MockCart) AddAdvertToCart(cartID, AdvertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAdvertToCart", cartID, AdvertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAdvertToCart indicates an expected call of AddAdvertToCart.
func (mr *MockCartMockRecorder) AddAdvertToCart(cartID, AdvertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAdvertToCart", reflect.TypeOf((*MockCart)(nil).AddAdvertToCart), cartID, AdvertID)
}

// CreateCart mocks base method.
func (m *MockCart) CreateCart(userID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", userID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockCartMockRecorder) CreateCart(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockCart)(nil).CreateCart), userID)
}

// DeleteAdvertFromCart mocks base method.
func (m *MockCart) DeleteAdvertFromCart(cartID, AdvertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdvertFromCart", cartID, AdvertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdvertFromCart indicates an expected call of DeleteAdvertFromCart.
func (mr *MockCartMockRecorder) DeleteAdvertFromCart(cartID, AdvertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdvertFromCart", reflect.TypeOf((*MockCart)(nil).DeleteAdvertFromCart), cartID, AdvertID)
}

// GetAdvertsByCartID mocks base method.
func (m *MockCart) GetAdvertsByCartID(cartID uuid.UUID) ([]entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertsByCartID", cartID)
	ret0, _ := ret[0].([]entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertsByCartID indicates an expected call of GetAdvertsByCartID.
func (mr *MockCartMockRecorder) GetAdvertsByCartID(cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertsByCartID", reflect.TypeOf((*MockCart)(nil).GetAdvertsByCartID), cartID)
}

// GetCartByID mocks base method.
func (m *MockCart) GetCartByID(cartID uuid.UUID) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByID", cartID)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByID indicates an expected call of GetCartByID.
func (mr *MockCartMockRecorder) GetCartByID(cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByID", reflect.TypeOf((*MockCart)(nil).GetCartByID), cartID)
}

// GetCartByUserID mocks base method.
func (m *MockCart) GetCartByUserID(userID uuid.UUID) (entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserID", userID)
	ret0, _ := ret[0].(entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserID indicates an expected call of GetCartByUserID.
func (mr *MockCartMockRecorder) GetCartByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserID", reflect.TypeOf((*MockCart)(nil).GetCartByUserID), userID)
}

// UpdateCartStatus mocks base method.
func (m *MockCart) UpdateCartStatus(tx pgx.Tx, cartID uuid.UUID, status entity.CartStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartStatus", tx, cartID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartStatus indicates an expected call of UpdateCartStatus.
func (mr *MockCartMockRecorder) UpdateCartStatus(tx, cartID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartStatus", reflect.TypeOf((*MockCart)(nil).UpdateCartStatus), tx, cartID, status)
}
