// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/seller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/go-park-mail-ru/2024_2_BogoSort/internal/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
)

// MockSeller is a mock of Seller interface.
type MockSeller struct {
	ctrl     *gomock.Controller
	recorder *MockSellerMockRecorder
}

// MockSellerMockRecorder is the mock recorder for MockSeller.
type MockSellerMockRecorder struct {
	mock *MockSeller
}

// NewMockSeller creates a new mock instance.
func NewMockSeller(ctrl *gomock.Controller) *MockSeller {
	mock := &MockSeller{ctrl: ctrl}
	mock.recorder = &MockSellerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeller) EXPECT() *MockSellerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockSeller) Add(tx pgx.Tx, userID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", tx, userID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockSellerMockRecorder) Add(tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSeller)(nil).Add), tx, userID)
}

// GetById mocks base method.
func (m *MockSeller) GetById(sellerID uuid.UUID) (*entity.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", sellerID)
	ret0, _ := ret[0].(*entity.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockSellerMockRecorder) GetById(sellerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockSeller)(nil).GetById), sellerID)
}

// GetByUserId mocks base method.
func (m *MockSeller) GetByUserId(userID uuid.UUID) (*entity.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", userID)
	ret0, _ := ret[0].(*entity.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockSellerMockRecorder) GetByUserId(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockSeller)(nil).GetByUserId), userID)
}
