// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/purchase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/go-park-mail-ru/2024_2_BogoSort/internal/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
)

// MockPurchaseRepository is a mock of PurchaseRepository interface.
type MockPurchaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseRepositoryMockRecorder
}

// MockPurchaseRepositoryMockRecorder is the mock recorder for MockPurchaseRepository.
type MockPurchaseRepositoryMockRecorder struct {
	mock *MockPurchaseRepository
}

// NewMockPurchaseRepository creates a new mock instance.
func NewMockPurchaseRepository(ctrl *gomock.Controller) *MockPurchaseRepository {
	mock := &MockPurchaseRepository{ctrl: ctrl}
	mock.recorder = &MockPurchaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseRepository) EXPECT() *MockPurchaseRepositoryMockRecorder {
	return m.recorder
}

// AddPurchase mocks base method.
func (m *MockPurchaseRepository) AddPurchase(tx pgx.Tx, purchase *entity.Purchase) (*entity.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPurchase", tx, purchase)
	ret0, _ := ret[0].(*entity.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPurchase indicates an expected call of AddPurchase.
func (mr *MockPurchaseRepositoryMockRecorder) AddPurchase(tx, purchase interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPurchase", reflect.TypeOf((*MockPurchaseRepository)(nil).AddPurchase), tx, purchase)
}

// BeginTransaction mocks base method.
func (m *MockPurchaseRepository) BeginTransaction() (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction")
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockPurchaseRepositoryMockRecorder) BeginTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockPurchaseRepository)(nil).BeginTransaction))
}

// GetPurchasesByUserID mocks base method.
func (m *MockPurchaseRepository) GetPurchasesByUserID(userID uuid.UUID) ([]*entity.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchasesByUserID", userID)
	ret0, _ := ret[0].([]*entity.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchasesByUserID indicates an expected call of GetPurchasesByUserID.
func (mr *MockPurchaseRepositoryMockRecorder) GetPurchasesByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchasesByUserID", reflect.TypeOf((*MockPurchaseRepository)(nil).GetPurchasesByUserID), userID)
}
