// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/advert.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/go-park-mail-ru/2024_2_BogoSort/internal/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
)

// MockAdvertRepository is a mock of AdvertRepository interface.
type MockAdvertRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertRepositoryMockRecorder
}

// MockAdvertRepositoryMockRecorder is the mock recorder for MockAdvertRepository.
type MockAdvertRepositoryMockRecorder struct {
	mock *MockAdvertRepository
}

// NewMockAdvertRepository creates a new mock instance.
func NewMockAdvertRepository(ctrl *gomock.Controller) *MockAdvertRepository {
	mock := &MockAdvertRepository{ctrl: ctrl}
	mock.recorder = &MockAdvertRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertRepository) EXPECT() *MockAdvertRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAdvertRepository) Add(advert *entity.Advert) (*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", advert)
	ret0, _ := ret[0].(*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockAdvertRepositoryMockRecorder) Add(advert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAdvertRepository)(nil).Add), advert)
}

// BeginTransaction mocks base method.
func (m *MockAdvertRepository) BeginTransaction() (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction")
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockAdvertRepositoryMockRecorder) BeginTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockAdvertRepository)(nil).BeginTransaction))
}

// DeleteById mocks base method.
func (m *MockAdvertRepository) DeleteById(advertId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", advertId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockAdvertRepositoryMockRecorder) DeleteById(advertId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockAdvertRepository)(nil).DeleteById), advertId)
}

// Get mocks base method.
func (m *MockAdvertRepository) Get(limit, offset int) ([]*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", limit, offset)
	ret0, _ := ret[0].([]*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdvertRepositoryMockRecorder) Get(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdvertRepository)(nil).Get), limit, offset)
}

// GetByCartId mocks base method.
func (m *MockAdvertRepository) GetByCartId(cartId uuid.UUID) ([]*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCartId", cartId)
	ret0, _ := ret[0].([]*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCartId indicates an expected call of GetByCartId.
func (mr *MockAdvertRepositoryMockRecorder) GetByCartId(cartId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCartId", reflect.TypeOf((*MockAdvertRepository)(nil).GetByCartId), cartId)
}

// GetByCategoryId mocks base method.
func (m *MockAdvertRepository) GetByCategoryId(categoryId uuid.UUID) ([]*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategoryId", categoryId)
	ret0, _ := ret[0].([]*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategoryId indicates an expected call of GetByCategoryId.
func (mr *MockAdvertRepositoryMockRecorder) GetByCategoryId(categoryId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategoryId", reflect.TypeOf((*MockAdvertRepository)(nil).GetByCategoryId), categoryId)
}

// GetById mocks base method.
func (m *MockAdvertRepository) GetById(advertId uuid.UUID) (*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", advertId)
	ret0, _ := ret[0].(*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAdvertRepositoryMockRecorder) GetById(advertId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAdvertRepository)(nil).GetById), advertId)
}

// GetBySellerId mocks base method.
func (m *MockAdvertRepository) GetBySellerId(sellerId uuid.UUID) ([]*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySellerId", sellerId)
	ret0, _ := ret[0].([]*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySellerId indicates an expected call of GetBySellerId.
func (mr *MockAdvertRepositoryMockRecorder) GetBySellerId(sellerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySellerId", reflect.TypeOf((*MockAdvertRepository)(nil).GetBySellerId), sellerId)
}

// Update mocks base method.
func (m *MockAdvertRepository) Update(advert *entity.Advert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", advert)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdvertRepositoryMockRecorder) Update(advert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdvertRepository)(nil).Update), advert)
}

// UpdateStatus mocks base method.
func (m *MockAdvertRepository) UpdateStatus(tx pgx.Tx, advertId uuid.UUID, status entity.AdvertStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", tx, advertId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAdvertRepositoryMockRecorder) UpdateStatus(tx, advertId, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAdvertRepository)(nil).UpdateStatus), tx, advertId, status)
}

// UploadImage mocks base method.
func (m *MockAdvertRepository) UploadImage(advertId, imageId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", advertId, imageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockAdvertRepositoryMockRecorder) UploadImage(advertId, imageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockAdvertRepository)(nil).UploadImage), advertId, imageId)
}
