// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/purchase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2024_2_BogoSort/internal/entity/dto"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPurchase is a mock of Purchase interface.
type MockPurchase struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseMockRecorder
}

// MockPurchaseMockRecorder is the mock recorder for MockPurchase.
type MockPurchaseMockRecorder struct {
	mock *MockPurchase
}

// NewMockPurchase creates a new mock instance.
func NewMockPurchase(ctrl *gomock.Controller) *MockPurchase {
	mock := &MockPurchase{ctrl: ctrl}
	mock.recorder = &MockPurchaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchase) EXPECT() *MockPurchaseMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockPurchase) Add(purchaseRequest dto.PurchaseRequest) (*dto.PurchaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", purchaseRequest)
	ret0, _ := ret[0].(*dto.PurchaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockPurchaseMockRecorder) Add(purchaseRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPurchase)(nil).Add), purchaseRequest)
}

// GetByUserId mocks base method.
func (m *MockPurchase) GetByUserId(userID uuid.UUID) ([]*dto.PurchaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", userID)
	ret0, _ := ret[0].([]*dto.PurchaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockPurchaseMockRecorder) GetByUserId(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockPurchase)(nil).GetByUserId), userID)
}
