// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/cart.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2024_2_BogoSort/internal/entity/dto"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCart is a mock of Cart interface.
type MockCart struct {
	ctrl     *gomock.Controller
	recorder *MockCartMockRecorder
}

// MockCartMockRecorder is the mock recorder for MockCart.
type MockCartMockRecorder struct {
	mock *MockCart
}

// NewMockCart creates a new mock instance.
func NewMockCart(ctrl *gomock.Controller) *MockCart {
	mock := &MockCart{ctrl: ctrl}
	mock.recorder = &MockCartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCart) EXPECT() *MockCartMockRecorder {
	return m.recorder
}

// AddAdvert mocks base method.
func (m *MockCart) AddAdvert(userID, AdvertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAdvert", userID, AdvertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAdvert indicates an expected call of AddAdvert.
func (mr *MockCartMockRecorder) AddAdvert(userID, AdvertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAdvert", reflect.TypeOf((*MockCart)(nil).AddAdvert), userID, AdvertID)
}

// CheckExists mocks base method.
func (m *MockCart) CheckExists(userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExists", userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExists indicates an expected call of CheckExists.
func (mr *MockCartMockRecorder) CheckExists(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExists", reflect.TypeOf((*MockCart)(nil).CheckExists), userID)
}

// DeleteAdvert mocks base method.
func (m *MockCart) DeleteAdvert(cartID, AdvertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdvert", cartID, AdvertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdvert indicates an expected call of DeleteAdvert.
func (mr *MockCartMockRecorder) DeleteAdvert(cartID, AdvertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdvert", reflect.TypeOf((*MockCart)(nil).DeleteAdvert), cartID, AdvertID)
}

// GetById mocks base method.
func (m *MockCart) GetById(cartID uuid.UUID) (dto.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", cartID)
	ret0, _ := ret[0].(dto.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockCartMockRecorder) GetById(cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCart)(nil).GetById), cartID)
}

// GetByUserId mocks base method.
func (m *MockCart) GetByUserId(userID uuid.UUID) (dto.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", userID)
	ret0, _ := ret[0].(dto.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockCartMockRecorder) GetByUserId(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockCart)(nil).GetByUserId), userID)
}
