// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/static.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStaticUseCase is a mock of StaticUseCase interface.
type MockStaticUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStaticUseCaseMockRecorder
}

// MockStaticUseCaseMockRecorder is the mock recorder for MockStaticUseCase.
type MockStaticUseCaseMockRecorder struct {
	mock *MockStaticUseCase
}

// NewMockStaticUseCase creates a new mock instance.
func NewMockStaticUseCase(ctrl *gomock.Controller) *MockStaticUseCase {
	mock := &MockStaticUseCase{ctrl: ctrl}
	mock.recorder = &MockStaticUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaticUseCase) EXPECT() *MockStaticUseCaseMockRecorder {
	return m.recorder
}

// GetAvatar mocks base method.
func (m *MockStaticUseCase) GetAvatar(staticID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar", staticID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatar indicates an expected call of GetAvatar.
func (mr *MockStaticUseCaseMockRecorder) GetAvatar(staticID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockStaticUseCase)(nil).GetAvatar), staticID)
}

// GetStaticURL mocks base method.
func (m *MockStaticUseCase) GetStaticURL(id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaticURL", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaticURL indicates an expected call of GetStaticURL.
func (mr *MockStaticUseCaseMockRecorder) GetStaticURL(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaticURL", reflect.TypeOf((*MockStaticUseCase)(nil).GetStaticURL), id)
}

// UploadFile mocks base method.
func (m *MockStaticUseCase) UploadFile(data []byte) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", data)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockStaticUseCaseMockRecorder) UploadFile(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockStaticUseCase)(nil).UploadFile), data)
}
