server:
  port: 8080
  host: localhost
  read_timeout: 10s
  write_timeout: 10s

session:
  expiration_time: 12h

pg_ip: localhost
pg_port: 5432
pg_user: postgres
pg_password: postgres
pg_db: emporiumdb
pg_timeout: 5s

static:
  path: static/
  max_size: 1048576