server:
  port: 8080
  grpc_port: 8081
  host: "0.0.0.0"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 10s

session:
  expiration_time: 12h
  secure_cookie: false

pg_ip: "localhost"
pg_port: 5432
pg_user: "postgres"
pg_password: "postgres"
pg_db: "emporiumdb"
pg_timeout: 5s

rd_addr: "localhost:6379"
rd_password: ""
rd_db: 0

csrf_secret: "2b7e151628aed2a6abf7158809cf4f3c"

static:
  path: "static/"
  max_size: 10485760
  timeout: 5s