server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 10s

session:
  expiration_time: 12h
  secure_cookie: false

auth_port: 50051
auth_host: "0.0.0.0"

pg_ip: "postgres"
pg_port: 8002
pg_user: "postgres"
pg_password: "postgres"
pg_db: "emporiumdb"
pg_timeout: 5s

rd_addr: "redis:6379"
rd_password: ""
rd_db: 0

csrf_secret: "2b7e151628aed2a6abf7158809cf4f3c"

static:
  path: "static/"
  max_size: 10485760
