server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 10s

session:
  expiration_time: 12h
  secure_cookie: false

auth_port: 50051
auth_host: "auth"

cart_purchase_host: "cart_purchase"
cart_purchase_port: 50052

static_host: "static"
static_port: 50053

pg_ip: "postgres"
pg_port: 5432
pg_user: "postgres"
pg_password: "postgres"
pg_db: "emporiumdb"
pg_timeout: 5s
pg_max_conns: 80

rd_addr: "redis:6379"
rd_password: ""
rd_db: 0

csrf_secret: "2b7e151628aed2a6abf7158809cf4f3c"

static:
  path: "static_files/"
  max_size: 31457280
  timeout: 5s
  port: 8081

search_batch_size: 100

db:
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m
  health_check_period: 1m

payment_shop_id: 998145
payment_secret: test_LIoGRqJoK8gUtvgGl-6NktRWnWPFFYhggwwvn5aHMZc
