definitions:
  handlers.AuthData:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handlers.LoginCredentials:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  responses.AuthErrResponse:
    properties:
      code:
        type: integer
      status:
        type: string
    type: object
  responses.AuthResponse:
    properties:
      email:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login a user with email and password or with a valid session cookie
        or Authorization header
      parameters:
      - description: User credentials
        in: body
        name: credentials
        schema:
          $ref: '#/definitions/handlers.LoginCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.AuthErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.AuthErrResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/responses.AuthErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.AuthErrResponse'
      summary: Login a user
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Signup a new user with email and password
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.AuthErrResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/responses.AuthErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.AuthErrResponse'
      summary: Signup a new user
      tags:
      - auth
swagger: "2.0"
