definitions:
  dto.Advert:
    properties:
      category_id:
        type: string
      description:
        type: string
      has_delivery:
        type: boolean
      id:
        type: string
      image_url:
        type: string
      location:
        type: string
      price:
        type: integer
      seller_id:
        type: string
      status:
        $ref: '#/definitions/dto.AdvertStatus'
      title:
        type: string
    type: object
  dto.AdvertStatus:
    enum:
    - active
    type: string
    x-enum-varnames:
    - AdvertStatusActive
  utils.ErrResponse:
    properties:
      code:
        type: integer
      status:
        type: string
    type: object
info:
  contact: {}
  title: "BogoSort API"
  version: "1.0"
paths:
  /api/v1/adverts:
    get:
      description: Get a list of all adverts
      parameters:
      - description: Limit the number of results
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of adverts
          schema:
            items:
              $ref: '#/definitions/dto.Advert'
            type: array
        "400":
          description: Invalid limit or offset
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to get adverts
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Get all adverts
      tags:
      - adverts
    post:
      consumes:
      - application/json
      description: Create a new advert
      parameters:
      - description: Advert data
        in: body
        name: advert
        required: true
        schema:
          $ref: '#/definitions/dto.Advert'
      produces:
      - application/json
      responses:
        "201":
          description: Advert created
          schema:
            $ref: '#/definitions/dto.Advert'
        "400":
          description: Invalid advert data
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to add advert
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Add a new advert
      tags:
      - adverts
  /api/v1/adverts/{advertId}:
    delete:
      description: Delete an advert by its ID
      parameters:
      - description: Advert ID
        in: path
        name: advertId
        required: true
        type: string
      responses:
        "204":
          description: Advert deleted
        "400":
          description: Invalid advert ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "404":
          description: Advert not found
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to delete advert
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Delete an advert by ID
      tags:
      - adverts
    get:
      description: Get an advert by its ID
      parameters:
      - description: Advert ID
        in: path
        name: advertId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Advert details
          schema:
            $ref: '#/definitions/dto.Advert'
        "400":
          description: Invalid advert ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "404":
          description: Advert not found
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to get advert by ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Get an advert by ID
      tags:
      - adverts
    put:
      consumes:
      - application/json
      description: Update an advert's information
      parameters:
      - description: Advert ID
        in: path
        name: advertId
        required: true
        type: string
      - description: Updated advert data
        in: body
        name: advert
        required: true
        schema:
          $ref: '#/definitions/dto.Advert'
      produces:
      - application/json
      responses:
        "200":
          description: Advert updated successfully
        "400":
          description: Invalid advert data
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "404":
          description: Advert not found
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to update advert
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Update an existing advert
      tags:
      - adverts
  /api/v1/adverts/{advertId}/status:
    put:
      description: Update advert status by ID
      parameters:
      - description: Advert ID
        in: path
        name: advertId
        required: true
        type: string
      - description: New status
        in: body
        name: status
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Advert status updated
        "400":
          description: Invalid advert ID or status
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "404":
          description: Advert not found
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to update advert status
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Update advert status
      tags:
      - adverts
  /api/v1/adverts/cart/{cartId}:
    get:
      description: Get a list of adverts in the specified cart
      parameters:
      - description: Cart ID
        in: path
        name: cartId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of adverts in cart
          schema:
            items:
              $ref: '#/definitions/dto.Advert'
            type: array
        "400":
          description: Invalid cart ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to get adverts by cart ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Get adverts by cart ID
      tags:
      - adverts
  /api/v1/adverts/user/{userId}:
    get:
      description: Get a list of adverts by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of adverts
          schema:
            items:
              $ref: '#/definitions/dto.Advert'
            type: array
        "400":
          description: Invalid user ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to get adverts by user ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Get adverts by user ID
      tags:
      - adverts
  /api/v1/adverts/user/{userId}/saved:
    get:
      description: Get a list of saved adverts by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of saved adverts
          schema:
            items:
              $ref: '#/definitions/dto.Advert'
            type: array
        "400":
          description: Invalid user ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Failed to get saved adverts by user ID
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Get saved adverts by user ID
      tags:
      - adverts
swagger: "2.0"
