name: BogoSort_2024_2 Deploy

on:
  push:
    branches: [main, develop, 'TP-*']
  pull_request:
    branches: [main, develop, 'TP-*']

jobs:
  run-linters:
    name: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
        id: go

      - name: Install required dependencies
        run: go mod tidy

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: .
          args: -c ./.golangci.yaml

  run-tests:
    name: run-tests
    needs: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Get Dependencies
        run: go get ./...

      - name: Build Application
        run: go build ./...

      - name: Run Tests
        run: go test ./... -v

  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection with New Key
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: "5.188.141.136" 
          username: "deployer"
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAPU1a6py
            Evq2ogWZJfiAL6AAAAGAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQDEP3EduJTo
            X7FHBZEYCe+uSeAKTBWTSTYJL16VUol8x4a8OOaz5TE5my7rrqGkmoV0hlsp65/Udo5ecZ
            GlMZE1aB/5VrwvV/Ztilwa1rQYd74GPy4Wp/7TZPZ+dEI7iXQy2g/l4Mm4m2oeu4frwJkl
            tcrNuehu4BL6DUM3X3io2JB3z8PY6JmgU8iNKiT2tBUSC+QLJB0gLAkHqMJ6Un3psINyKW
            RXEM1VAjgAuseRrLOdQp+NneNM8ZsD+DSQ2D++1LAHuJmaPoGOydgxNv7L+x1S7QRItrRO
            uTbR2VJUChqOeKjX+y5oOiNf18JQXP/uzVFXd5LRsKBGedAJxzMeNdBfV5H16D4TV5dLXl
            9pVTvTA2vj+B6AMTaUzgX9Bzoxd8/9BnoZOg1iT252ArwyoHUCriZyzxpJEqWmjQzEWwBO
            WVqQrpGYtTBSXGH/IH1O2FZwzBDbeXMPMKLu0J1cuD9gb/dpUqhoSxuw6lJHJfsV7cleMl
            xBLmJLLzFgrIozU7wk2LN0ocEBuAkEy9b/NbVXtvHLlRnNOxJF7FTY/nJo8Kx7A9fnjqFX
            s5qz1jcQftDGDIgXmBn7S5zn1elURT56QN+WiKnMH31W25ZYkEkp4rzT/qgpk1pqO2KA+D
            y3c3TCG/+O1qpL3Bn9ZrXfRo9ABeTdyxhvYbW5TAJzcQAAB1D4JrT7t3QumfXB5SgFB+o4
            XLz21wBlFoeCvTsLzxeEfBuX0+PmrxdQPB8kmByrgwA7BvhTgLdw8u1W4rEhepxZgrbiis
            3mnWjjymWyDveQS3ZvvorynEsli9xOV5bP9IGF7EZFTFy0jKkXu5CdXur0JxGXX10+Nw1L
            VbkyX6IIG30gmXm7XLVakB8aHDWrW2e/ANF3AanTBNiV/JHumjV1ognIAwia11+a3XqW9X
            +HIQBgHgK65jES6LHycsYIXPwHggMWR6F6B6EU6iKhPWCSd5GtHtEH4RyOCCaprd0YhBz+
            7SX+PEdLBgjlTOBwom2o1rXrHpXWxXMCLWNVBE5AmRW5NAHJQrpZ9XJI/qf57HZDzOfV/n
            pbXMRMt6pxURmSzQHwsMjSnXyddmfLOuiq2txkOviry3K241LiX+O40uqDKIVuoSEih37H
            m5Ds09I2CFdb0iaGgXrtNR8r4A47SPUxaA3wwBY9b55A4yIdHss8uJF7JDvaL7N1B05aZh
            F4vWSEpnmpknwPHmMqFFa4htxXvjSIFnlTTmsL4mH2/Ni8WPgJW/T5P6SM4rnNBp1Uuuu+
            HsjEmBi8c8vcguCyuXZng3aq1zbvYqIjOmsztMepVulVcACf4YysnywjB0IedudVAH3djn
            m70JhtwMvNe4tdeeAHwfCUBNEr3APf1s5cDGZR31PDl9ZxbLeQ4x1DhsWzvhPCdgdQblFN
            rSA8hf3nwvjWhDxCSSW06Yj0nSDWDs9iPwGWaLi5GUeWthpUc8Sw+GMPZfv683OVyChZXt
            JoFikVP/roSaLs+0ATVd4PDxyHQal9v4XcR3j1YM+iHIOrMgYabn/DedHjoWkvV7oqcHm5
            GJJtkl15dyvsWl33ue7uKPfh7w7dFokjX38GI6xK2W2dncHhu0gjsCFE5rPF5B4jn99xG9
            G7WakECNFI+//vHkTMjIiJgTNlJYcU6e7SNLaufag+8h6uR39FZxhzYfyEWqBzlm/k7fTk
            LDIPZOHqEfaG4xsHZ4oqhV4ik+a1z2QcKif+0RukBCSwGyHB5k5oEZXwuWtiCPZqqReC7O
            6rQVFYxowE4R2Cc3EX5mU0dp6U+t525lRfmLq3B4l3HlllGqOsRth2fBDLaAzWrAWvCqOx
            54IMIBh/SHrb08qcKaYYfftNtu/pnxwP9GTSunVXqGrfItcfsmsVCoxijE5gio6WSieuCL
            S38GYFjvX/jYTwaWFv/KcEwrND+SAg9mj557KVh7DrNghUQ7OZBL2v/VI3c81XDjfOFAhb
            6LH1fuP/+8qjCGLC3YxRziKsNp87h5rUqFCm2qUMzS0Yn88tDuuB4i2GUyKdedC2zrC927
            mwnCqNHkgOFwt9mLBTn+R8uhUkRTf+Uj5EiZ9TfqpTCNmcmqgR/0HrSdb1Zuz3fvV3szjt
            jny0Iut3avnH+5oV3I3hl+lFJSDvXGd+R6sSp67lcIkljISBEugO/2F6g1Bmqt12xc21T3
            DpcD7cG3YBp2E2i9O0sL0pCKFnn5xkE8PGt/8/Xil50I6/sI1zAYmFoHJ/AwbTpXu/oQas
            uhpfQX5Rm9YfZLLzEPdQKy3lNqLW4n4I1xZTW6OVMqn15h3buy2yKKWeYZg6mwFTwxUOFK
            b393N55EfQhI/2Z9Aya2I7PJZuVWqhU0G0eFlqPDAaMG5swUOT8qtbPa5iXEr5ghAZKuax
            OK3FGRXKdq56fhpMWyD5WhhFo9hjmYYMCDoEybCAb+Pn9rzVUG8ntorhT5cPyvo/8oYtJG
            NG8HhA/ajbzb2kpC4USmlKMW3+EZ32/5fj0DZ6OQXqRzkGW2HPk3auX7VkMotEpDO9jq/x
            CRgeOaGfM7I5WSTAtxNVk5n405CWoKBDsss2x2DSSO70lZk0CilwoVqS2dgbNZNzFjidqN
            zosIDkJtmmo0kCYNrZ48W5hHGGGGraCJZeovgER01JW4kCW35kNpt8CpBv3lVTbM8na9gE
            /rAAFYD187CI6jA4x9Gf1UAzdWrF6Eh84+FR7SI+HwI00AVUE+iHNE9WhioF5UP9t0qMQz
            SsADl9J/gvd84WUxSn6io0rOXrgb5ha4oIWYBfVJtwkPYOydFs5Dz8YQMrH4pqEVyOElcT
            u5iyemAWUm3GK576B/NtTpg2LfCcH9OlAXhdNm02fz02IaagukkXaGQnV7hOFdIAyILAqh
            9d5sEBxqp3vjYPE62Foerk6TXvwHTLDrftOvvg8XGYoiuzh3KMLHRgz18TIeW6zTEorO8X
            BMJ8NA7Rv2NOCnVSrIYbTrIFOfeksC06uit6nST5TscjaP3BH71Gp/ycXf3Cozx3FcwPiL
            2SMhjYGAmleqhYu6gsVNnczs13zPJJd1KgZ6odAOtRCt96Vu7K3TJ/JtFUJ60Z1lARekiq
            K6pbmATJ0L6DBIRSbvjrrR2i6+9AzhAHipxLaW8nd8LQOcPkJcdb1lVlYZRm2pCZViZ3C4
            qCtWU93jvw8kaqaL6EqM3QjEY=
            -----END OPENSSH PRIVATE KEY-----
          port: 22 
          debug: true
          script: |
            echo "SSH Connection Successful"
            hostname

  deploy:
    name: Deploy to Server
    if: github.ref == 'refs/heads/TP-34_add_ci'
    needs: [run-linters, run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          debug: true
          script: |
            cd /home/${{ secrets.USERNAME }}/server/back
            git checkout develop
            git fetch && git pull
            sudo docker-compose build
            sudo docker-compose down
            sudo docker-compose up -d --build --remove-orphans

